// Dev tool: diagnose nondeterminism. Captures frame t after different seek histories and diffs them.
import { chromium } from 'playwright';
import http from 'node:http'; import fs from 'node:fs'; import path from 'node:path'; import { execFileSync } from 'node:child_process';
const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '../..');
const T = Number(process.argv[2] || 0), PRE = (process.argv[3] || '24').split(',').map(Number);
const out = path.join(ROOT, 'review/detdiag'); fs.mkdirSync(out, { recursive: true });
const server = http.createServer((q, r) => { const f = path.join(ROOT, decodeURIComponent(new URL(q.url, 'http://x').pathname)); if (!fs.existsSync(f)) { r.writeHead(404); r.end(); return; } r.writeHead(200, { 'content-type': f.endsWith('.js') ? 'text/javascript' : f.endsWith('.css') ? 'text/css' : f.endsWith('.json') ? 'application/json' : f.endsWith('.html') ? 'text/html' : f.endsWith('.woff2') ? 'font/woff2' : 'application/octet-stream' }); fs.createReadStream(f).pipe(r); });
await new Promise((r) => server.listen(0, r));
const EXTRA = (process.env.CHROME_EXTRA || '').split(' ').filter(Boolean);
const b = await chromium.launch({ args: ['--force-color-profile=srgb', '--font-render-hinting=none', '--disable-lcd-text', '--hide-scrollbars', '--disable-font-subpixel-positioning', ...EXTRA] });
const ctx = await b.newContext({ viewport: { width: 1920, height: 1080 }, colorScheme: 'dark', reducedMotion: 'reduce' });
const p = await ctx.newPage(); const cdp = await ctx.newCDPSession(p);
await p.goto(`http://127.0.0.1:${server.address().port}/film/index.html`);
await p.waitForFunction(() => window.__ready !== undefined); await p.evaluate(() => window.__ready);
const HIDE = (process.env.HIDE || '').split(',').filter(Boolean);
if (HIDE.length) await p.addStyleTag({ content: HIDE.map((h) => `${h}{visibility:hidden!important}`).join('\n') });
if (process.env.REATTACH) await p.evaluate(() => { const o = window.seek; window.seek = (t) => { o(t); const st = document.getElementById('stage'); const par = st.parentNode, nx = st.nextSibling; par.removeChild(st); par.insertBefore(st, nx); }; });
const grab = async (name) => { const { data } = await cdp.send('Page.captureScreenshot', { format: 'png' }); fs.writeFileSync(path.join(out, name), Buffer.from(data, 'base64')); };
const state = () => p.evaluate(() => { const o = []; let i = 0; for (const el of document.querySelectorAll('#stage *')) { i++; const attrs = [...el.attributes].map((a) => a.name + '=' + a.value).join(' '); const own = [...el.childNodes].filter((n) => n.nodeType === 3).map((n) => n.textContent).join(''); const val = el.value !== undefined && typeof el.value === 'string' ? ' value=' + el.value : ''; o.push(i + ':' + el.tagName + ' ' + attrs + ' #' + own.trim().slice(0, 40) + val); } return o; });
await p.evaluate((t) => seek(t), T); await grab('a.png'); const sa = await state();
await p.evaluate((t) => seek(t), T); await grab('a2.png');
for (const pre of PRE) await p.evaluate((t) => seek(t), pre);
await p.evaluate((t) => seek(t), T); await grab('b.png'); const sb = await state();
const cmp = (x, y) => { try { execFileSync('compare', ['-metric', 'AE', path.join(out, x), path.join(out, y), path.join(out, `diff_${x}_${y}`)], { stdio: ['ignore', 'ignore', 'pipe'] }); return '0'; } catch (e) { return String(e.stderr); } };
console.log('same t twice  AE =', cmp('a.png', 'a2.png'));
console.log('after scrub   AE =', cmp('a.png', 'b.png'));
const setA = new Set(sa), setB = new Set(sb);
const onlyA = sa.filter((x) => !setB.has(x)), onlyB = sb.filter((x) => !setA.has(x));
console.log('style diffs:', onlyA.length, onlyB.length);
onlyA.slice(0, 12).forEach((x, i) => console.log('A:', x.slice(0, 220), '\nB:', (onlyB[i] || '').slice(0, 220)));
await b.close(); server.close();
